### ISSUE TITLE
Contact Info

### ISSUE THREAD

**Issue by TempusShift** [knocktrends/knocksensor#2]
Team Contact Info

**Comment by TempusShift** [comment]
AJ Deck, ajd4223@rit.edu, (502)552-4592

**Comment by corbanmailloux** [comment]
Corban Mailloux, cdm3806@rit.edu, (413) 522-7625

**Comment by kmb4577** [comment]
Kaitlin B, kmb4577@rit.edu, (518) 524-3403

**Comment by phillip2048** [comment]
Zach Calfin, zpc4747@rit.edu, 856-318-9224

**Comment by Matthew-Crawford** [comment]
Matthew Crawford, mjc5454@rit.edu, (518)580-1260

**Comment by JakeDarling** [comment]
Jake Darling, jtd7523@rit.edu, (315)360-2938

**Comment by kmb4577** [comment]
Kaitlin Brockway, kmb4577@rit.edu, (518)524-3403
